name: Node.js Build

on:
  push:
    branches: [ "main" ] # Runs whenever you push to the main branch
  workflow_dispatch: # Allows you to run the build manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify your required Node version
        cache: 'npm' # Speeds up future builds by caching dependencies

    - name: Install dependencies
      run: npm install

    - name: Run Build
      run: npm run build

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
